---
plugin: vultr.cloud.vultr
api_key: "{{ lookup('env', 'VULTR_API_KEY') }}"
compose:
  ansible_host: vultr_main_ip
  postgresql_version: "16"
keyed_groups:
  - key: vultr_tags | lower
    prefix: ''
    separator: ''
